# Generated by Django 3.1.6 on 2021-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
